title: nobu.ltd
headerStyle: clean
statusStyle: "dot"
hideVersion: true
showStats: true
fullWidth: false
maxGroupColumns: 4
useEqualHeights: true
background:
  image: https://images.steamusercontent.com/ugc/1777212268232389646/9B0340A269AABD0962C625AC5AC7A7E3BC4BE2BF/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false
  # image: https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3
  blur: ""
  saturate: 100
  brightness: 75
  opacity: 90
layout:
  System:
    style: row
    columns: 4
  Services:
    style: row
    columns: 3
    header: false
    Infrastructure:
      style: row
      columns: 2
    Media:
      style: row
      columns: 2
    Tools:
      style: row
      columns: 2
